// Builds src/data/hanzi.ts — Mandarin pinyin + Chinese definitions for every
// CJK character, so the camera OCR can show what a character means in CHINESE
// usage (as opposed to its Japanese readings, which come from KANJI_BASE).
//
// Source: Unicode's Unihan database (Unihan_Readings.txt):
//   kMandarin   → the most common Mandarin reading, in pinyin
//   kDefinition → a short English definition of the Chinese usage
// Run: node scripts/build-hanzi.mjs
import { writeFile, mkdir, readFile, rm } from 'node:fs/promises'
import { execFileSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { tmpdir } from 'node:os'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const work = join(tmpdir(), 'unihan-build')
const ZIP = 'https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip'

await mkdir(work, { recursive: true })
const zipPath = join(work, 'Unihan.zip')

console.log('Downloading Unihan database…')
const res = await fetch(ZIP)
if (!res.ok) throw new Error(`Unihan.zip: HTTP ${res.status}`)
await writeFile(zipPath, Buffer.from(await res.arrayBuffer()))

console.log('Extracting Unihan_Readings.txt…')
execFileSync('unzip', ['-o', '-q', zipPath, 'Unihan_Readings.txt', '-d', work])
const text = await readFile(join(work, 'Unihan_Readings.txt'), 'utf8')

const pinyin = new Map()
const defs = new Map()
for (const line of text.split('\n')) {
  if (line.startsWith('#') || !line.trim()) continue
  const [code, field, ...rest] = line.split('\t')
  const value = rest.join('\t').trim()
  if (!code?.startsWith('U+')) continue
  const ch = String.fromCodePoint(parseInt(code.slice(2), 16))
  if (field === 'kMandarin') pinyin.set(ch, value.split(/\s+/)[0])
  else if (field === 'kDefinition') {
    // keep the first two senses; they are already English
    defs.set(ch, value.split(';').slice(0, 2).join(';').trim())
  }
}

// Only ship characters that have at least a pinyin reading.
const chars = [...pinyin.keys()].sort()
const body = chars
  .map((ch) => {
    const d = defs.get(ch)
    const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
    return d
      ? `  '${esc(ch)}': ['${esc(pinyin.get(ch))}', '${esc(d)}'],`
      : `  '${esc(ch)}': ['${esc(pinyin.get(ch))}'],`
  })
  .join('\n')

const out = `// AUTO-GENERATED by scripts/build-hanzi.mjs — do not edit by hand.
// Mandarin pinyin and Chinese-usage definitions from the Unicode Unihan
// database (kMandarin, kDefinition). Used by the camera OCR's Chinese mode.
// Tuple: [pinyin, definition?]
export const HANZI: Record<string, [string, string?]> = {
${body}
}
`
await writeFile(join(root, 'src', 'data', 'hanzi.ts'), out, 'utf8')
await rm(work, { recursive: true, force: true })
console.log(`Wrote src/data/hanzi.ts with ${chars.length} characters (${defs.size} with definitions).`)
